// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRProject.API.Context;

#nullable disable

namespace RRProject.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240222234501_AppDbInicial")]
    partial class AppDbInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RRProject.API.Entities.AvaliacaoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidataIdenti")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaApresentacao")
                        .HasColumnType("int");

                    b.Property<int>("NotaBeleza")
                        .HasColumnType("int");

                    b.Property<int>("NotaFantasia")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioIdenti")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("RRProject.API.Entities.Candidata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrlcandidata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrlclube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clube = "Assembleia Paraense",
                            ImagemUrlcandidata = "/Imagens/Candidatas/assembleia.png",
                            ImagemUrlclube = "/Imagens/Clubes/assembleia.png",
                            Nome = "Fernanda Costa"
                        },
                        new
                        {
                            Id = 2,
                            Clube = "Bancrévea",
                            ImagemUrlcandidata = "/Imagens/Candidatas/bancrevea.png",
                            ImagemUrlclube = "/Imagens/Clubes/bancrevea.png",
                            Nome = "Vitorya Carolyne"
                        },
                        new
                        {
                            Id = 3,
                            Clube = "Casota",
                            ImagemUrlcandidata = "/Imagens/Candidatas/casota.png",
                            ImagemUrlclube = "/Imagens/Clubes/casota.png",
                            Nome = "Letícia Moraes"
                        },
                        new
                        {
                            Id = 4,
                            Clube = "Cassazum",
                            ImagemUrlcandidata = "/Imagens/Candidatas/cassazum.png",
                            ImagemUrlclube = "/Imagens/Clubes/cassazum.png",
                            Nome = "Natália Leão"
                        },
                        new
                        {
                            Id = 5,
                            Clube = "Clube de Engenharia",
                            ImagemUrlcandidata = "/Imagens/Candidatas/engenharia.png",
                            ImagemUrlclube = "/Imagens/Clubes/engenharia.png",
                            Nome = "Heloysa Rodrigues"
                        },
                        new
                        {
                            Id = 6,
                            Clube = "Clube do Remo",
                            ImagemUrlcandidata = "/Imagens/Candidatas/remo.png",
                            ImagemUrlclube = "/Imagens/Clubes/remo.png",
                            Nome = "Gabrielle Costa"
                        },
                        new
                        {
                            Id = 7,
                            Clube = "Clube dos Advogado",
                            ImagemUrlcandidata = "/Imagens/Candidatas/oab.png",
                            ImagemUrlclube = "/Imagens/Clubes/oab.png",
                            Nome = "Lídia Negrão"
                        },
                        new
                        {
                            Id = 8,
                            Clube = "Grêmio Português ",
                            ImagemUrlcandidata = "/Imagens/Candidatas/gremio.png",
                            ImagemUrlclube = "/Imagens/Clubes/gremio.png",
                            Nome = "Ana Karina"
                        },
                        new
                        {
                            Id = 9,
                            Clube = "Acqua Park",
                            ImagemUrlcandidata = "/Imagens/Candidatas/guara.png",
                            ImagemUrlclube = "/Imagens/Clubes/guara.png",
                            Nome = "Giselly Geise"
                        },
                        new
                        {
                            Id = 10,
                            Clube = "Pará Clube",
                            ImagemUrlcandidata = "/Imagens/Candidatas/clubepara.png",
                            ImagemUrlclube = "/Imagens/Clubes/clubepara.png",
                            Nome = "Evelyn Moreira"
                        },
                        new
                        {
                            Id = 11,
                            Clube = "Paysandu",
                            ImagemUrlcandidata = "/Imagens/Candidatas/paysandu.png",
                            ImagemUrlclube = "/Imagens/Clubes/paysandu.png",
                            Nome = "Tais Malato"
                        },
                        new
                        {
                            Id = 12,
                            Clube = "Tênis Clube",
                            ImagemUrlcandidata = "/Imagens/Candidatas/tenis.png",
                            ImagemUrlclube = "/Imagens/Clubes/tenis.png",
                            Nome = "Ana Maria Marques"
                        },
                        new
                        {
                            Id = 13,
                            Clube = "Tuna Luso",
                            ImagemUrlcandidata = "/Imagens/Candidatas/tuna.png",
                            ImagemUrlclube = "/Imagens/Clubes/tuna.png",
                            Nome = "Ingrid Kácia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
