// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRProject.API.Context;

#nullable disable

namespace RRProject.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RRProject.API.Entities.Candidata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Apresentacao")
                        .HasColumnType("int");

                    b.Property<int>("Beleza")
                        .HasColumnType("int");

                    b.Property<string>("Clube")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Fantasia")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Candidatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Paysandu",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Paysandu.png",
                            Nome = "Rayane Furtado",
                            Total = 0
                        },
                        new
                        {
                            Id = 2,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Grêmio Literário e Recreativo Português",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Grêmio Literário e Recreativo Português.png",
                            Nome = "Giovanna Cristinne Silva Picanço",
                            Total = 0
                        },
                        new
                        {
                            Id = 3,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Assembleia Paraense",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Assembléia Paraense.png",
                            Nome = "Isadora Andrade Rêgo",
                            Total = 0
                        },
                        new
                        {
                            Id = 4,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Bancrévea",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Bancrévea.png",
                            Nome = "Érica Venise da Silva Pinto",
                            Total = 0
                        },
                        new
                        {
                            Id = 5,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Guará Acqua Park",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Guará Acqua Park.png",
                            Nome = "Aline Carla Rodrigues Wanderley",
                            Total = 0
                        },
                        new
                        {
                            Id = 6,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "ASALP",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/ASALP.png",
                            Nome = "Ádria Mayara Pantoja Nogueira",
                            Total = 0
                        },
                        new
                        {
                            Id = 7,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Tuna Luso Brasileira ",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Tuna Luso Brasileira.png",
                            Nome = "Janaína Pontes Ferreira",
                            Total = 0
                        },
                        new
                        {
                            Id = 8,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Tênis Clube do Pará",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Tênis Clube.png",
                            Nome = "Ana de Nazaré Martins Barbosa",
                            Total = 0
                        },
                        new
                        {
                            Id = 9,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Clube do Remo",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Clube do Remo.png",
                            Nome = "Adriana dos Santos Pinheiro",
                            Total = 0
                        },
                        new
                        {
                            Id = 10,
                            Apresentacao = 0,
                            Beleza = 0,
                            Clube = "Iate Clube de Santarém",
                            Fantasia = 0,
                            ImagemUrl = "/Imagens/Candidatas/Iate Clube de Santarém.png",
                            Nome = "Monã Rita Vianna de Oliveira",
                            Total = 0
                        });
                });

            modelBuilder.Entity("RRProject.API.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Senha")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
